# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: release

on: workflow_dispatch
  
jobs:
  build:
    runs-on: windows-latest 
    
    permissions:
      actions: write
      deployments: write
      repository-projects: write
      packages: write
      contents: write
      
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
        
    - name: create
      run: dotnet pack
      working-directory: PowerCollections
      
    - name: publish
      run: dotnet nuget push "PowerCollections\bin\Debug\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/readq1/index.json --skip-duplicate
      working-directory: PowerCollections
      
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with: 
        xml-file: 'PowerCollections/PowerCollections/PowerCollections.csproj'
        xpath: '//Version'
        
    - name: release 
      uses: ncipollo/release-action@v1.12.0
      with: 
        artifacts: 'PowerCollections\PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}.nupkg'
        tag: ${{ steps.getxml.outputs.info }}
